### ISSUE TITLE
Test Pipeline Update View Manager Put

### ISSUE THREAD

**Issue by shanearcaro** [jenniferNeto/ColPal#14]
'NoneType' object has no attribute 'update_reason'
Cause is backend/pipeline/view.py, perform_update_now()

Caused by #8

**Comment by shanearcaro** [comment]
Bug fixed in 72a3c970c90f9d8201fc28a79f6b341a1c2e244c
